id: productListingPage
name: Product Listing Page
icon: view-list
parameters: []
useTeamPermissions: true
slots:
  - id: top
    name: Top
    allowedComponents:
      - plpHeader
      - callToAction
    inheritAllowedComponents: false
  - id: sidebar
    name: Sidebar
    allowedComponents:
      - plpRefinements
    inheritAllowedComponents: false
  - id: main
    name: Main
    allowedComponents:
      - plpListing
      - plpFooter
    inheritAllowedComponents: false
  - id: emptySearchResults
    name: Empty Search Results
    allowedComponents:
      - plpNoResults
    inheritAllowedComponents: false
  - id: refinementsModal
    name: Refinements Modal
    allowedComponents:
      - plpRefinements
    inheritAllowedComponents: false
  - id: editorial
    name: Editorial
    allowedComponents:
      - callToAction
      - features
    inheritAllowedComponents: false
slugSettings:
  unique: 'no'
  required: 'yes'
  regularExpression: ''
  regularExpressionMessage: ''
canBeComposition: true
created: '2022-12-10T00:02:34.956753+00:00'
updated: '2022-12-10T00:11:05.019472+00:00'
