id: productDetailPage
name: Product Detail Page
icon: shopping-cart
parameters: []
useTeamPermissions: true
slots:
  - id: main
    name: Main
    allowedComponents:
      - pdpProductInformation
      - pdpProductView
    inheritAllowedComponents: false
  - id: editorial
    name: Editorial
    allowedComponents:
      - pdpRecommendedProducts
      - productRecommendations
      - features
      - callToAction
    inheritAllowedComponents: false
canBeComposition: true
created: '2022-10-21T00:33:16.92682+00:00'
updated: '2022-11-16T17:35:04.26849+00:00'
