id: productRecommendations
name: Product Recommendations
icon: bulb
parameters:
  - id: title
    name: Title
    type: text
    helpText: ''
    typeConfig:
      required: false
  - id: products
    name: Products
    type: salesforce-cc-einstein
    helpText: ''
    typeConfig: null
useTeamPermissions: true
slots: []
titleParameter: title
canBeComposition: false
created: '2022-12-10T00:02:35.150275+00:00'
updated: '2022-12-10T00:11:05.329157+00:00'
