id: productDetailPage
name: Product Detail Page
icon: shopping-cart
parameters: []
useTeamPermissions: true
slots:
  - id: main
    name: Main
    allowedComponents:
      - pdpProductInformation
      - pdpProductView
    inheritAllowedComponents: false
  - id: editorial
    name: Editorial
    allowedComponents:
      - pdpRecommendedProducts
      - productRecommendations
      - features
      - callToAction
    inheritAllowedComponents: false
canBeComposition: true
created: '2022-12-10T00:02:34.927995+00:00'
updated: '2022-12-10T00:11:05.163463+00:00'
