id: productRail
name: Product Rail
icon: view-list
parameters:
  - id: title
    name: Title
    type: text
    typeConfig:
      required: true
  - id: text
    name: Text
    type: text
    helpText: ''
    typeConfig:
      multiline: true
      linesCount: '6'
  - id: products
    name: Products
    type: salesforce-cc-product-selector
    helpText: ''
    typeConfig:
      variant: false
      multiple: true
useTeamPermissions: true
slots: []
titleParameter: title
canBeComposition: false
created: '2022-12-10T00:02:35.030636+00:00'
updated: '2022-12-10T00:11:05.084122+00:00'
